k8s_config:
- manifest_path: /yaml
  cluster_info:
    cluster_id: 16bb0016-3600-58d5-a4c2-a81856baac57
    cluster_name: Quote Demo cluster
- manifest_path: /manifest
  cluster_info:
    cluster_id: 37caa869-8e68-52a5-af6b-fe3b96c517f3
    cluster_name: Quote Demo cluster
