---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-mapping
spec:
  hostname: "demo.ryan.k736.net"
  prefix: /
  service: quotefrontend
  cors:
    origins: 
    - "http://demo.ryan.k736.net"
