---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-host
spec:
  acmeProvider:
    email: marekojames@datawire.io
  hostname: "demo1.kjames.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-mapping
spec:
  hostname: "demo1.kjames.k736.net"
  prefix: /
  service: quotefrontend
  cors:
    origins: 
    - "http://demo1.kjames.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-api
spec:
  hostname: "demo1.kjames.k736.net"
  prefix: "/quote/"
  service: quote.default
  labels:
    ambassador:
    - label_group:
      - generic_key:
          value: test-limit
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimit
metadata:
  name: default-rate-limit
spec:
  domain: ambassador
  limits:
  - pattern:
    - generic_key: "test-limit"
    rate: 3
    unit: minute
    burstFactor: 3
