---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-host
  namespace: demo
spec:
  acmeProvider:
    email: marekojames@datawire.io
  hostname: "demo.kjames.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-api
  namespace: demo
spec:
  hostname: "demo.kjames.k736.net"
  prefix: /quote/
  service: quote.default:80
  docs:
    path: "/.ambassador-internal/openapi-docs"