---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: example-host
spec:
  acmeProvider:
    email: marekojames@datawire.io
  hostname: "demo1.kjames.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-mapping
spec:
  hostname: "demo1.kjames.k736.net"
  prefix: /
  service: quotefrontend
  cors:
    origins: 
    - "http://demo1.kjames.k736.net"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-api
spec:
  hostname: "demo1.kjames.k736.net"
  prefix: "/quote/"
  service: quote.default

