apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: quote-rollout
spec:
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - image: docker.io/marekojames5298/quote
          imagePullPolicy: Always
          name: quote
          ports:
            - containerPort: 8080
  strategy:
    canary:
      stableService: quote
      canaryService: quote-canary
      trafficRouting:
        ambassador:
          mappings:
            - quote-backend
      steps:
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 100
      - pause: {duration: 10}
