---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: ambassador
spec:
  secretName: ambassador-certs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - ryan.k736.net
---