
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    defaults:
      httpmapping:
        add_response_headers:
          strict-transport-security: "max-age=31536000; includeSubDomains"