---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotefrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/marekojames5298/quote-front
        ports:
        - name: http
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: quotefrontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: frontend
---
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-frontend
  namespace: demo
spec:
  hostname: "*"
  prefix: /home/
  service: quotefrontend.default:80
