apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout
spec:
  replicas: 5
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quote
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
