apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-rollout
spec:
  replicas: 1
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quote
  strategy:
    canary:
      stableService: quote  # must match your service name
      canaryService: quote-canary  # must match your service name
      trafficRouting:  # this section required to use Edge Stack for routing
        ambassador:
          mappings:
            - quote-backend
      steps:
        - setWeight: 20
        - pause: {duration: 10s}
